apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus-operator-config

commonAnnotations:
  "helm.sh/resource-policy": keep

commonLabels:
  app: prometheus-operator
  managedBy: argocd
  managementCodeGroup: chrismlee42-dev
  managementCodeProject: prometheus-operator-config

namespace: prometheus-operator

resources:
  # Determine latest stable version from https://github.com/prometheus-operator/prometheus-operator/releases
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.84.1/bundle.yaml
  - namespace.yaml
